############################################
# CloudTechNext Select AI Apex inputs
############################################

variable "tenancy_ocid" {
  description = "Tenancy OCID."
  type        = string
}

variable "user_ocid" {
  description = "OCI user OCID for local CLI use. Resource Manager leaves this empty."
  type        = string
  default     = ""
}

variable "fingerprint" {
  description = "OCI API key fingerprint for local CLI use. Resource Manager leaves this empty."
  type        = string
  default     = ""
}

variable "private_key_path" {
  description = "OCI private key path for local CLI use. Resource Manager leaves this empty."
  type        = string
  default     = ""
}

variable "compartment_ocid" {
  description = "Target compartment OCID."
  type        = string
  default     = ""
}

variable "region" {
  description = "OCI region, for example us-chicago-1."
  type        = string

  validation {
    condition     = length(var.region) > 0
    error_message = "region cannot be empty."
  }
}

variable "objectstorage_namespace" {
  description = "Object Storage namespace resolved by CloudTechNext for Resource Manager stack variable parity."
  type        = string
  default     = ""
}

variable "deployment_suffix" {
  description = "Unique suffix generated by CloudTechNext for this deployment."
  type        = string
  default     = "local0000"

  validation {
    condition     = can(regex("^[a-z0-9]{4,16}$", var.deployment_suffix))
    error_message = "deployment_suffix must be 4 to 16 lowercase alphanumeric characters."
  }
}

variable "adb_db_name" {
  description = "Unique Autonomous Database db_name for this deployment."
  type        = string
  default     = ""

  validation {
    condition     = var.adb_db_name == "" || can(regex("^[A-Za-z][A-Za-z0-9]{1,13}$", var.adb_db_name))
    error_message = "adb_db_name must start with a letter, contain only letters and numbers, and be at most 14 characters."
  }
}

variable "adb_display_name" {
  description = "Autonomous Database display name for this deployment."
  type        = string
  default     = ""
}

variable "autonomous_database_mode" {
  description = "Whether Select AI Apex should create a new Autonomous Database or use an existing one."
  type        = string
  default     = "new"

  validation {
    condition     = contains(["new", "existing"], var.autonomous_database_mode)
    error_message = "autonomous_database_mode must be new or existing."
  }
}

variable "existing_autonomous_database_ocid" {
  description = "Existing Autonomous Database OCID when autonomous_database_mode is existing."
  type        = string
  default     = ""

  validation {
    condition     = var.existing_autonomous_database_ocid == "" || can(regex("^ocid1\\.autonomousdatabase\\.", var.existing_autonomous_database_ocid))
    error_message = "existing_autonomous_database_ocid must be empty or an Autonomous Database OCID."
  }
}

variable "autonomous_database_version" {
  description = "Autonomous Database version to provision for Select AI Apex."
  type        = string
  default     = "26ai"

  validation {
    condition     = contains(["26ai", "19c"], var.autonomous_database_version)
    error_message = "autonomous_database_version must be 26ai or 19c."
  }
}

variable "autonomous_database_workload" {
  description = "Autonomous Database workload to provision for Select AI Apex. Use DW for Lakehouse or OLTP for Transaction Processing."
  type        = string
  default     = "DW"

  validation {
    condition     = contains(["DW", "OLTP"], var.autonomous_database_workload)
    error_message = "autonomous_database_workload must be DW or OLTP."
  }
}

variable "source_ref" {
  description = "Git ref selected in Deploy Studio for traceability."
  type        = string
  default     = "main"
}

variable "select_ai_grant_schemas" {
  description = "Comma-separated schema list whose tables should be granted to the Select AI Apex profile owner."
  type        = string
  default     = "SH_DEMO"

  validation {
    condition     = length(trimspace(var.select_ai_grant_schemas)) > 0
    error_message = "select_ai_grant_schemas cannot be empty."
  }
}

variable "select_ai_apex_app_id" {
  description = "Repository APEX application id installed by the post-apply hook."
  type        = string
  default     = "chatdb-es-2024"

  validation {
    condition     = contains(["chatdb-es-2024", "ask-oracle-chatbot"], var.select_ai_apex_app_id)
    error_message = "select_ai_apex_app_id must be chatdb-es-2024 or ask-oracle-chatbot."
  }
}

variable "_oci_autonomous_database" {
  description = "Scalable Autonomous Database profile for Select AI Apex launchpad deployments."

  default = {
    compute_count            = 4
    data_storage_size_in_tbs = 1
    is_auto_scaling_enabled  = true
  }
}

variable "autonomous_database_admin_password" {
  description = "ADMIN password for Autonomous Database."
  type        = string
  sensitive   = true
  default     = ""

  validation {
    condition = (
      var.autonomous_database_admin_password == "" || (
        length(var.autonomous_database_admin_password) >= 12 &&
        length(var.autonomous_database_admin_password) <= 30 &&
        can(regex("[A-Z]", var.autonomous_database_admin_password)) &&
        can(regex("[a-z]", var.autonomous_database_admin_password)) &&
        can(regex("[0-9]", var.autonomous_database_admin_password)) &&
        !can(regex("\"", var.autonomous_database_admin_password)) &&
        !can(regex("'", var.autonomous_database_admin_password)) &&
      !can(regex("(?i)admin", var.autonomous_database_admin_password)))
    )
    error_message = "Password must be 12-30 characters, include uppercase, lowercase and number, and cannot contain quotes or admin."
  }
}

variable "autonomous_database_wallet_password" {
  description = "Wallet password for Autonomous Database."
  type        = string
  sensitive   = true
  default     = ""

  validation {
    condition = (
      var.autonomous_database_wallet_password == "" || (
        length(var.autonomous_database_wallet_password) >= 12 &&
        length(var.autonomous_database_wallet_password) <= 30 &&
        can(regex("[A-Z]", var.autonomous_database_wallet_password)) &&
        can(regex("[a-z]", var.autonomous_database_wallet_password)) &&
        can(regex("[0-9]", var.autonomous_database_wallet_password)) &&
        !can(regex("\"", var.autonomous_database_wallet_password)) &&
        !can(regex("'", var.autonomous_database_wallet_password)) &&
      !can(regex("(?i)admin", var.autonomous_database_wallet_password)))
    )
    error_message = "Password must be 12-30 characters, include uppercase, lowercase and number, and cannot contain quotes or admin."
  }
}

variable "autonomous_database_developer_password" {
  description = "Select AI Apex APEX workspace administrator password."
  type        = string
  sensitive   = true
  default     = ""

  validation {
    condition = (
      var.autonomous_database_developer_password == "" || (
        length(var.autonomous_database_developer_password) >= 1 &&
        length(var.autonomous_database_developer_password) <= 128 &&
        !can(regex("\"", var.autonomous_database_developer_password)) &&
      !can(regex("[\\r\\n]", var.autonomous_database_developer_password)))
    )
    error_message = "Application password must be 1-128 characters and cannot contain double quotes or line breaks."
  }
}

variable "application_username" {
  description = "Select AI Apex APEX workspace administrator username."
  type        = string
  default     = "SELECT_AI_ADMIN"

  validation {
    condition = (
      can(regex("^[A-Za-z0-9][A-Za-z0-9_.@-]{0,127}$", var.application_username))
    )
    error_message = "Application username must start with a letter or number and can include letters, numbers, _, ., @ or -."
  }
}
