from pathlib import Path

DEFAULT_WORKSPACE = "SELECT_AI_APEX"
DEFAULT_APP_SCHEMA = "SELECT_AI_APP"
DEFAULT_PROFILE_NAME = "GROK_REASONING"
DEFAULT_MODEL = "xai.grok-4-fast-reasoning"
DEFAULT_CREDENTIAL_NAME = "OCI_GENAI_CRED"
DEFAULT_APEX_ALIAS = "SELECT_AI_APEX"
DEFAULT_APEX_APP_NAME = "Autonomous DB + Select AI"
DEFAULT_APEX_USER = "SELECT_AI_ADMIN"
DEFAULT_OUTPUT_DIR = Path("outputs")
DEFAULT_APEX_ARCHIVE = Path("apex/chatdb-es-2024.sql")

SQL_OBJECT_TYPES = ("TABLE", "VIEW", "MATERIALIZED VIEW")
